# -*- coding: utf-8 -*-
"""820 final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F_pqR7Cdn3ESPjWZZs7akhtJt3akZ86h
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset

from google.colab import files
uploaded = files.upload()

"""# Loading Basic Libraries"""

import pandas as pd

df = pd.read_csv("df.csv")

"""#Data Pre-Processing

"""

# Preview of data
df.head(15)

#List of variable types
df.info()

"""##Missing Values
3 columns, all categorical, contain missing values.
"""

df[df == ' ?'].count()

"""Removing the rows which contain missing values (listwise)."""

df2 = df[df['workclass'] != ' ?']
df2 = df2[df2['occupation'] != ' ?']
df2 = df2[df2['native-country'] != ' ?']
df2
df2.info()

"""Rerunning missing values code to ensure it worked"""

df2[df2 == ' ?'].count()

"""# Descriptives

Shape of the dataframe:
"""

print('Shape of dataframe:', df.shape)
df2.head()

"""##Numeric Variables

Descriptive statistics about numeric data after removing missing values. We can ignore fnlwgt for now is it does not correspond to a demographic variable.
"""

df2.describe()

"""##Categorical Variables

Descriptive statistics and count values for categorical data.
"""

df2['workclass'].value_counts().to_frame().head(15)

df2['education'].value_counts().to_frame().head(15)

df2['marital-status'].value_counts().to_frame().head(15)

df2['occupation'].value_counts().to_frame().head(15)

df2['relationship'].value_counts().to_frame().head(15)

df2['race'].value_counts().to_frame().head(15)

df2['sex'].value_counts().to_frame().head(15)

df2['native-country'].value_counts().to_frame().head(15)

"""##Predictor Variable"""

df2['income'].value_counts().to_frame().head(15)